import Head from "next/head"
import Footer from "./Footer"

export const baseAppTitle = "Coffee Conoisseur"

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Coffee Shop finder Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=KoHo:wght@400;600;700&family=La+Belle+Aurore&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        {children}
      </main>
      <Footer />
    </>
  )
}

export default Layout